language: python
python:
- '2.7'
node_js:
- '0.10'
addons:
  firefox: '30.0'
env:
  matrix:
  - DJANGO=django==1.5.4
  global:
  - secure: gJ/2vz3uLrvEAodhI/uchCZYM7z0eFidAGP3kj2wD5rhUlaMvFZZd1EApJjSxBsxUnJwcdXZdpcy1GM2hx2c2vpNF8YEwm42dsQwvKUHveP+8bBxeB+zp0KoikdDDIUQKu2gjUv4n/QRZzCpEvmFdHtn6/yXnlyV6g5axUYCQyE=
  - secure: nhtUS6j9oU38XHd5nl0MsorrqAhSukSWGU/R31hWT6NT4ipUmYLJniIerHCJ+Vt++h4XH3CSYmBRYYEiRrx81kBhlbxGdPm1cGVLb76NCjdhjUsiqoS5yB8H056/GnZWlYYG2ZaWOYgHhACTlQpm5OICO6TILLYcSd362Fg+gKs=
services:
- memcached
before_install:
- gem update --system
- gem install compass -v 0.12.7
- npm install -g grunt-cli
- npm install grunt grunt-contrib-compass
- sudo apt-get install -qq memcached python-memcache libjpeg8-dev libjpeg-dev zlib1g-dev libpng12-dev
- pip install Pillow --use-mirrors
install:
- pip install --upgrade setuptools --use-mirrors
- pip install $DJANGO --use-mirrors
- pip install --use-mirrors --use-wheel --find-links=https://stream.onepercentclub.com/wheelhouse/ -r requirements/ci_requirements.txt
- touch onepercentclub/settings/secrets.py
before_script:
- pip show bluebottle
- grunt compass:dist --bb_path="`pip show bluebottle | grep Location | cut -b11-`/bluebottle/common/static/sass"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#- curl https://gist.githubusercontent.com/rollick/42b92c18c3a265b08792/raw/sauce-connect.sh | sh
script:
- python ./manage.py test --settings=onepercentclub.settings.travis -v1 --failfast
notifications:
  hipchat:
    rooms:
      secure: lfQxEnp7TBqzVc61Wm8NhQiqkKg6YBSx9Ro1q3VTeUWsKzFS2p7OV1eKu8bXjCA9FaCaaxc/TxFaZcvUr2hzXJiW/VoZH4J/+yYp2yblhj5uzQuQl3oWRgY8eFK33rjelqnkolFSmrMkVWY6cw/M8DNrxoSqzQLP2Dn5jYxS6Jg=
